database: x_product
spring:
  application:
    name: product-service
  config:
    import:
      - nacos:datasource
      - nacos:product-service
      - nacos:registry
  cloud:
    nacos:
      config:
        server-addr: 10.3.9.47
        namespace:
        file-extension: yaml